import { motion } from "framer-motion";
import { Leaf, TreePine, Factory, Recycle } from "lucide-react";
import { Header } from "@/components/Header";
import { Footer } from "@/components/Footer";

const LearnMore = () => {
  const sections = [
    {
      icon: <Leaf className="w-8 h-8 text-primary-600" />,
      title: "What is a Carbon Footprint?",
      content:
        "A carbon footprint is the total amount of greenhouse gases (including carbon dioxide and methane) that are generated by our actions. Understanding your carbon footprint is the first step toward making environmentally conscious decisions.",
    },
    {
      icon: <TreePine className="w-8 h-8 text-primary-600" />,
      title: "Why It Matters",
      content:
        "Climate change is one of the biggest challenges facing our planet. Every individual's actions contribute to global emissions, and by reducing our carbon footprint, we can help combat climate change and preserve the environment for future generations.",
    },
    {
      icon: <Factory className="w-8 h-8 text-primary-600" />,
      title: "Sources of Carbon Emissions",
      content:
        "Carbon emissions come from various sources in our daily lives, including transportation, home energy use, food consumption, and waste production. By identifying these sources, we can make informed decisions to reduce our impact.",
    },
    {
      icon: <Recycle className="w-8 h-8 text-primary-600" />,
      title: "How to Reduce Your Impact",
      content:
        "There are many ways to reduce your carbon footprint, from using public transportation and energy-efficient appliances to reducing waste and choosing renewable energy sources. Small changes in daily habits can make a significant difference.",
    },
  ];

  return (
    <div className="min-h-screen">
      <Header />
      <div className="min-h-screen pt-16 bg-gradient-to-b from-primary-50 to-white">
        <div className="container mx-auto px-4 py-16">
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.5 }}
            className="text-center max-w-3xl mx-auto"
          >
            <h1 className="text-4xl font-bold mb-4 text-gray-900">
              Understanding Carbon Footprint
            </h1>
            <p className="text-lg text-gray-600 mb-12">
              Learn about carbon emissions and how you can make a difference in
              protecting our planet.
            </p>
          </motion.div>

          <div className="grid grid-cols-1 md:grid-cols-2 gap-8 max-w-6xl mx-auto">
            {sections.map((section, index) => (
              <motion.div
                key={index}
                initial={{ opacity: 0, y: 20 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ duration: 0.5, delay: index * 0.1 }}
                className="bg-white rounded-xl shadow-lg p-6"
              >
                <div className="flex items-center mb-4">
                  {section.icon}
                  <h2 className="text-2xl font-semibold ml-4 text-gray-900">
                    {section.title}
                  </h2>
                </div>
                <p className="text-gray-600 leading-relaxed">{section.content}</p>
              </motion.div>
            ))}
          </div>
        </div>
      </div>
      <Footer />
    </div>
  );
};

export default LearnMore;